// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdHf1oUwm9gioFyhtJmYVUvnlwAfEhFBI',
    appId: '1:916476343485:web:d09888143212ba9ca133d4',
    messagingSenderId: '916476343485',
    projectId: 'flutter-gymapp-56d7a',
    authDomain: 'flutter-gymapp-56d7a.firebaseapp.com',
    storageBucket: 'flutter-gymapp-56d7a.appspot.com',
    measurementId: 'G-6VB2FZXWVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCagLps5xFy4VM3S3fpmbIxny2XTUCaQDM',
    appId: '1:916476343485:android:3f797504b495edb9a133d4',
    messagingSenderId: '916476343485',
    projectId: 'flutter-gymapp-56d7a',
    storageBucket: 'flutter-gymapp-56d7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIY-WP-55JHyKqdY9U8smmn0A-mRmYLw4',
    appId: '1:916476343485:ios:ace130333fb11485a133d4',
    messagingSenderId: '916476343485',
    projectId: 'flutter-gymapp-56d7a',
    storageBucket: 'flutter-gymapp-56d7a.appspot.com',
    iosBundleId: 'gayoso.diego.flutterMyFirstApp',
  );
}
